### ISSUE TITLE
Nest Away button nothing happen

### ISSUE THREAD

**Issue by dartflag** [FilipDem/Domoticz-NEST-plugin#29]
Hi Filip, very good job to create this workaround for Nest ;)
I installed yesterday the plugin you created on my Raspberry Pi.
no problem for the installation, and no error when I launch Domoticz, and same thing when I tested the nest plugin.

But when I click on the Nest Away button, nothing happen. I have no problem with all others Nest buttons.

are you aware about this issue? Do you have a solution about it?

thanks a lot for your help

Fred

**Comment by FilipDem** [comment]
Hi Fred,

You are right... Since I did a refactoring some months ago to support also the Nest Protect status etc, the Away device did not only depend the Nest Thermostat (as it is a generic status for all the nest devices)... However seems there was still one line of code where this was pending... Solved now in the latest version.

Btw: If you are happy about the plugin and the support, don't hesitate for a small contribution for all my hours of work (no obligation).

Filip

**Comment by dartflag** [comment]
Hi Filip,
I put the new plugin file, and now, it works fine ;)
thanks very much for your very quick help
Fred
