### ISSUE TITLE
Error: Nest Thermostat hardware (10) thread seems to have ended unexpectedly

### ISSUE THREAD

**Issue by Jesse-Klaasse** [FilipDem/Domoticz-NEST-plugin#3]
I have added the plugin to my Domoticz (running @ Synology DS418play), and configured it. However, I get this in domoticz.log: Error: Nest Thermostat hardware (10) thread seems to have ended unexpectedly

When I run nest.py, I get this:

```
jesse@diskstation:/usr/local/domoticz/var/plugins/Domoticz-NEST-plugin# python3 nest.py
Traceback (most recent call last):
  File "nest.py", line 231, in <module>
    thermostat.GetDevicesAndStatus()
  File "nest.py", line 172, in GetDevicesAndStatus
    if self.status['topaz']:
KeyError: 'topaz'
```

**Comment by FilipDem** [comment]
Seems I got not published the right version on GitHub... Need to check, but can do it perhaps only this weekend. 
I suppose you don't have a NEST Protect. Can you confirm?
In that case could you change the line 172 to "if 'topaz' in self.status:" instead of "if self.status['topaz']:". In my feeling it should then work... Give me feedback please so that I change on GitHub then.

**Comment by FilipDem** [comment]
I had the change to take a quick look and for any reason, I didn't seem to have my latest version posted. This one should do the trick. Could you verify and give feedback?

**Comment by Jesse-Klaasse** [comment]
Hi @FilipDem . I have updated the plugin to your new version, and now it's working fine. Thanks a lot!
