### ISSUE TITLE
Domoticz is freezing up

### ISSUE THREAD

**Issue by Rednas79** [FilipDem/Domoticz-NEST-plugin#36]
Hello, i.m. in the proces of replacing my RPI 3B for a 4B with RPI Bullseye on it.

Got everything working aspect this plugin.
Installation is no issue, after restarting Domoticz i can select the plugin.
I copy past the issue_token and cookie for the previous installation and press add domoticz crash.
I seem to keep running, but there is no hardware (can't even select other build in plugins), and devices aren't even loaded.

I need to delete the plugin folder to get domoticz back working again.

Even check for new issue_token / cookie, but same effect.
Plugin is still workin in on the 3B

**Comment by FilipDem** [comment]
I considered also migrating to Bulleye, however didn't do it because of the clear warning on the Domoticz wiki. Please see:
[https://www.domoticz.com/wiki/Raspberry_Pi](https://www.domoticz.com/wiki/Raspberry_Pi)
![image](https://user-images.githubusercontent.com/16196363/153840045-396ec244-67b6-4666-89ed-c90c6bf24518.png)

And I run regularly in the same problem as mentioned on [https://github.com/dnpwwo/Domoticz-Google-Plugin](https://github.com/dnpwwo/Domoticz-Google-Plugin) 
![image](https://user-images.githubusercontent.com/16196363/153840378-34b6a878-d6ad-49e7-a1b8-13b4c77d88f2.png)

**Comment by Rednas79** [comment]
ok check, thnx will wait with the migration abit then.
